name: Test Cosmos

on:
  pull_request:
    branches:
      - main
      - feature/*
      - release/*

permissions: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Start Cosmos Emulator
        run: |
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          Start-CosmosDbEmulator -Timeout 360

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore
        run: restore.cmd
        shell: cmd

      - name: Build
        run: build.cmd /p:Projects=${{ github.workspace }}\test\EFCore.Cosmos.FunctionalTests\EFCore.Cosmos.FunctionalTests.csproj
        shell: cmd

      - name: Test on Cosmos
        run: test.cmd /p:Projects=${{ github.workspace }}\test\EFCore.Cosmos.FunctionalTests\EFCore.Cosmos.FunctionalTests.csproj
        shell: cmd

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: artifacts/log/Debug/*

  build-mssql:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server
        env:
          SA_PASSWORD: Password12!
          ACCEPT_EULA: Y
        ports: [1433]

    env:
      Test__SqlServer__DefaultConnection: Data Source=(local)\MSSQLSERVER;Initial Catalog=master;User ID=sa;Password=Password12!;Connect Timeout=60;ConnectRetryCount=0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore
        run: restore.cmd
        shell: cmd

      - name: Build
        run: ./build.sh /p:Projects=${{ github.workspace }}/test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj

      - name: Test on Cosmos
        run: ./test.sh /p:Projects=${{ github.workspace }}/test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-mssql
          path: artifacts/log/Debug/*

